[package]
name = "picacg_api"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "PicACG API 客户端库"

[dependencies]
picacg_core = { path = "../picacg_core" }
picacg_config = { path = "../picacg_config" }

reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
parking_lot.workspace = true
tracing.workspace = true
urlencoding.workspace = true
hmac.workspace = true
sha2.workspace = true
hex.workspace = true
uuid.workspace = true
